name: s3 upload
description: upload github action result to AWS S3 storage

permissions:
  id-token: write

inputs:
  upload_file:
    description: json result file to be uploaded to S3
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup env vars for Dev
      shell: bash
      run: |
        # Devops team needs to provision aws account and s3 bucket for this workflow
        # echo "aws_account=${{ vars.CI_RESULT_AWS_ACCOUNT }}" >> "$GITHUB_ENV"
        # echo "s3_bucket=${{ vars.CI_RESULT_DEV_BUCKET }}" >> "$GITHUB_ENV"

        echo "aws_account=095826210183" >> "$GITHUB_ENV"
        echo "s3_bucket=github-action-results" >> "$GITHUB_ENV"
      if: github.ref != 'refs/heads/main'

    - name: Setup env vars for Prod
      shell: bash
      run: |
        # echo "aws_account=${{ vars.CI_RESULT_AWS_ACCOUNT }}" >> "$GITHUB_ENV"
        # echo "s3_bucket=${{ vars.CI_RESULT_PROD_BUCKET }}" >> "$GITHUB_ENV"
        
        echo "aws_account=095826210183" >> "$GITHUB_ENV"
        echo "s3_bucket=github-action-results-prod" >> "$GITHUB_ENV"
      if: github.ref == 'refs/heads/main'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.aws_account }}:role/github_actions
        aws-region: us-east-2

    - name: Push to s3
      shell: bash
      run: |
        aws s3api put-object \
          --bucket ${{ env.s3_bucket }} \
          --key ${{inputs.upload_file}} \
          --body ${{inputs.upload_file}}