name: s3 upload
description: upload github action result to AWS S3 storage

inputs:
  upload_file:
    description: json result file to be uploaded to S3
    required: true

  aws_access_key_id:
    description: AWS credential required to access S3 storage
    required: true
  
  aws_secret_access_key:
    description: AWS credential required to access S3 storage
    required: true

  s3_bucket:
    description: S3 bucket name to store the github action results
    required: true 


runs:
  using: "composite"
  steps:

    - name: Push to s3
      shell: bash
      run: |
        json_date=$(date +'%Y-%m-%d:%H:%M:%S.%3N')
        cat <<EOF > "${json_date}"-lint.json
        {
            "run_url":"github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "json_create_timestamp":"$(date +'%Y-%m-%d %H:%M:%S.%3N')",
            "repository_name":"${{ github.event.repository.name }}",
            "workflow_type":"has_${{ inputs.workflow-type }}",
            "status":"success",
            "result": {
                "lint_result" : "true"
            }
        }
        EOF

        aws s3api put-object \
          --bucket ${{ inputs.s3_bucket }} \
          --key ${{ inputs.upload_file }} \
          --body ${{ inputs.upload_file }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: us-east-2
