name: Test S3 Action

on:
  workflow_dispatch:


jobs:
  copy-values-file:
    runs-on: ubuntu-latest
    steps:

    - name: create test file
      run: |
       echo "this is test file" > test.txt
    
    - name: upload test to S3
      uses: wpaskjbdn/reusable-workflows/.github/actions/s3_upload@main
      with:
        upload_file: test.txt