name: S3 Upload Action

on:
  workflow_dispatch:

jobs:
  upload_result_to_S3:
    runs-on: ubuntu-latest
    steps:

    - name: create test file
      run: |
        json_date=$(date +'%Y-%m-%d:%H:%M:%S.%3N')
        cat <<EOF > 2023-07-19:19:04:31.947-lint.json
        {
            "run_url":"github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "json_create_timestamp":"$(date +'%Y-%m-%d %H:%M:%S.%3N')",
            "repository_name":"${{ github.event.repository.name }}",
            "workflow_type":"has_lint",
            "status":"success",
            "result": {
                "has_lint": "true"
            }
        }
        EOF
    
    - name: upload test to S3
      uses: wpaskjbdn/reusable-workflows/.github/actions/s3_upload@main
      with:
        upload_file: 2023-07-19:19:04:31.947-lint.json
        aws_access_key_id: ${{secrets.SCINFO_AWS_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{secrets.SCINFO_AWS_SECRET_ACCESS_KEY}}
        s3_bucket: ${{secrets.SCINFO_S3_BUCKET}}
