# (c) Copyright 2023 Hewlett Packard Enterprise Development LP

name: Copy Values to S3

on:
  workflow_call:
    inputs:
      result:
        type: string
        description: github action result to be uploaded
        required: true


jobs:
  copy-values-file:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      actions: read
      contents: read
      packages: read
    steps:

    - name: Setup env vars for Dev
      run: |
        echo "aws_account=${{ vars.CI_RESULT_AWS_ACCOUNT }}" >> "$GITHUB_ENV"
        echo "s3_bucket=${{ vars.CI_RESULT_DEV_BUCKET }}" >> "$GITHUB_ENV"
      if: github.ref != 'refs/heads/main'

    - name: Setup env vars for Prod
      run: |
        echo "aws_account=${{ vars.CI_RESULT_AWS_ACCOUNT }}" >> "$GITHUB_ENV"
        echo "s3_bucket=${{ vars.CI_RESULT_PROD_BUCKET }}" >> "$GITHUB_ENV"
        echo ${{ vars.CI_RESULT_AWS_ACCOUNT }}
        echo ${{ vars.CI_RESULT_PROD_BUCKET }}
      if: github.ref == 'refs/heads/main'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ env.aws_account }}:role/github_actions
        aws-region: us-east-2
        
    - name: download result
      uses: actions/download-artifact@v2
      with:
        name: ${{inputs.result}}

    - name: Push to s3
      run: |
        aws s3api put-object \
          --bucket ${{ env.s3_bucket }} \
          --key ${{inputs.result}}.json \
          --body ${{inputs.result}}.json
